### ISSUE TITLE
Readme improvement

### ISSUE THREAD

**Issue by apilaskowski** [buyuk-dev/tomography-2D#1]
I suggest inserting some exemplary pictures of the whole process.
The procedure has three steps, it would be really nice to have the visualization in Readme file.

**Comment by buyuk-dev** [comment]
will do, but first need to implement filtering :)

**Comment by apilaskowski** [comment]
Since filtering is done... I am just reminding about this issue. :)

**Comment by buyuk-dev** [comment]
quick update, ive included sample results screenshot in readme :)
